apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ${NAMESPACE}
  name: ${IDENTIFIER}-monitoring-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: '${IDENTIFIER}-monitoring-job'
        static_configs:
          - targets: ['${IDENTIFIER}-monitoring-agent:9187']
