apiVersion: v1
kind: ConfigMap

metadata:
  namespace: ${NAMESPACE}
  name: monitoring-server-settings

data:
  prometheus.yml: |
    scrape_configs:
    - job_name: '${IDENTIFIER}'
      scrape_interval: 5s
      static_configs:
      - targets: ['monitoring-agent:9187']
