apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  namespace: ${NAMESPACE}
  name: ${LABEL}
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:${VERSION}
  imagePullPolicy: always
  instances: ${NODES_COUNT}
  monitoring:
    enablePodMonitor: true
  storage:
    size: ${STORAGE_DATA_SIZE}Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: ${NAMESPACE}
  name: ${LABEL}-ingress-primary
spec:
  type: LoadBalancer
  selector:
    role: primary
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  namespace: ${NAMESPACE}
  name: ${LABEL}-ingress-replicas
spec:
  type: LoadBalancer
  selector:
    role: replica
  ports:
    - port: 5432
      targetPort: 5432