# Definition of the backup schedule.
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup

metadata:
  namespace: ${NAMESPACE}
  name: ${IDENTIFIER}-backup

spec:
  # Cron based format.
  schedule: "${DATABASE_BACKUP_SCHEDULE}"
  suspend: false
  immediate: true
  backupOwnerReference: self
  cluster:
    name: ${IDENTIFIER}