# Definition of credentials for the cluster authentication.
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth

metadata:
  namespace: ${NAMESPACE}
  name: auth-secret

data:
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
---
# Definition of credentials for the cluster backup.
apiVersion: v1
kind: Secret

metadata:
  namespace: ${NAMESPACE}
  name: backup-secret

data:
  accessKey: ${DATABASE_BACKUP_ACCESS_KEY}
  secretKey: ${DATABASE_BACKUP_SECRET_KEY}