# Definition of the stack credentials for authentication and backups.
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth

metadata:
  namespace: ${NAMESPACE}
  name: ${IDENTIFIER}-auth-secret

data:
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
---
apiVersion: v1
kind: Secret

metadata:
  namespace: ${NAMESPACE}
  name: ${IDENTIFIER}-backup-secret

data:
  accessKey: ${DATABASE_BACKUP_ACCESS_KEY}
  secretKey: ${DATABASE_BACKUP_SECRET_KEY}
---
apiVersion: v1
kind: Secret

metadata:
  namespace: ${NAMESPACE}
  name: ${IDENTIFIER}-monitoring-secret

data:
  connectionString: ${DATABASE_CONNECTION_STRING}
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
