# Definition of the cluster credentials for authentication and backups.
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth

metadata:
  namespace: ${NAMESPACE}
  name: ${IDENTIFIER}-auth-secret

data:
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
---
apiVersion: v1
kind: Secret

metadata:
  namespace: ${NAMESPACE}
  name: ${IDENTIFIER}-backup-secret

data:
  ACCESS_KEY_ID: ${DATABASE_BACKUP_ACCESS_KEY}
  ACCESS_SECRET_KEY: ${DATABASE_BACKUP_SECRET_KEY}