# Definition of cluster services (primary & replicas).
apiVersion: v1
kind: Service

metadata:
  namespace: ${NAMESPACE}
  name: primary

spec:
  type: LoadBalancer

  selector:
    role: primary

  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service

metadata:
  namespace: ${NAMESPACE}
  name: replicas

spec:
  type: LoadBalancer

  selector:
    role: replica

  ports:
    - port: 5432
      targetPort: 5432