# Definition of the stack load balancers (primary, replicas and monitoring).
apiVersion: v1
kind: Service

metadata:
  namespace: ${NAMESPACE}
  name: ${IDENTIFIER}-primary

spec:
  type: LoadBalancer

  selector:
    role: primary

  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service

metadata:
  namespace: ${NAMESPACE}
  name: ${IDENTIFIER}-replicas

spec:
  type: LoadBalancer

  selector:
    role: replica

  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service

metadata:
  namespace: ${NAMESPACE}
  name: ${IDENTIFIER}-monitoring-agent

spec:
  selector:
    app: ${IDENTIFIER}-monitoring-agent

  ports:
    - protocol: TCP
      port: 9187
      targetPort: 9187
---
apiVersion: v1
kind: Service

metadata:
  namespace: ${NAMESPACE}
  name: ${IDENTIFIER}-monitoring

spec:
  type: LoadBalancer

  selector:
    app: ${IDENTIFIER}-monitoring

  ports:
    - port: 9090
      targetPort: 9090