# Definition of the cluster load balancers (primary and replicas).
apiVersion: v1
kind: Service

metadata:
  namespace: ${NAMESPACE}
  name: ${IDENTIFIER}-ingress-primary

spec:
  type: LoadBalancer

  selector:
    role: primary

  ports:
    - port: ${DATABASE_PORT}
      targetPort: ${DATABASE_PORT}
---
apiVersion: v1
kind: Service

metadata:
  namespace: ${NAMESPACE}
  name: ${IDENTIFIER}-ingress-replicas

spec:
  type: LoadBalancer

  selector:
    role: replica

  ports:
    - port: ${DATABASE_PORT}
      targetPort: ${DATABASE_PORT}