# Definition of cluster services (primary & replicas).
apiVersion: v1
kind: Service

metadata:
  namespace: ${NAMESPACE}
  name: primary

spec:
  type: LoadBalancer

  selector:
    role: primary

  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service

metadata:
  namespace: ${NAMESPACE}
  name: replicas

spec:
  type: LoadBalancer

  selector:
    role: replica

  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service

metadata:
  namespace: ${NAMESPACE}
  name: monitoring-agent

spec:
  selector:
    app: monitoring-agent

  ports:
    - port: 9187
      targetPort: 9187
---
apiVersion: v1
kind: Service

metadata:
  namespace: ${NAMESPACE}
  name: monitoring-server

spec:
  type: LoadBalancer

  selector:
    app: monitoring-server

  ports:
    - port: 9090
      targetPort: 9090
