services:
  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./fullchain.pem:/etc/tls/certs/fullchain.pem
      - ./privkey.pem:/etc/tls/private/privkey.pem

    depends_on:
      - grafana

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: